# Generated by Django 5.1.7 on 2025-03-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0003_contactsubmission_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='description',
        ),
    ]
