# Generated by Django 5.1.7 on 2025-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0004_remove_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
