# Generated by Django 5.1.7 on 2025-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0008_pendinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='learn_more_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
