# Generated by Django 5.1.7 on 2025-03-28 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0010_package_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('data', 'Data'), ('voice', 'Voice'), ('sms', 'SMS'), ('combo', 'Combo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='validity',
            field=models.PositiveIntegerField(help_text='Validity in hours'),
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('receiving_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
