# Generated by Django 5.1.7 on 2025-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0011_alter_package_type_alter_package_validity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagepurchase',
            name='is_successful',
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('data', 'Data'), ('voice', 'Voice'), ('sms', 'SMS')], max_length=100),
        ),
    ]
