# Generated by Django 5.1.7 on 2025-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0012_remove_packagepurchase_is_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
