# Generated by Django 5.1.7 on 2025-03-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0014_datapackage_delete_packagepurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPackage',
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price']},
        ),
    ]
