# Generated by Django 5.1.7 on 2025-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0015_delete_datapackage_alter_package_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
    ]
