# Generated by Django 5.1.7 on 2025-04-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0017_alter_package_options_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
