# Generated by Django 5.1.7 on 2025-04-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0019_alter_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ussd_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ussd_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ussd_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='USSDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('mpesa_ref', models.CharField(max_length=50)),
                ('payment_number', models.CharField(max_length=15)),
                ('receiving_number', models.CharField(max_length=15)),
                ('ussd_code', models.CharField(max_length=100)),
                ('server_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_logs', to='Inno.transaction')),
            ],
            options={
                'verbose_name': 'USSD Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
