# Generated by Django 5.1.7 on 2025-04-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0020_transaction_ussd_code_transaction_ussd_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['package_id']},
        ),
        migrations.RenameField(
            model_name='package',
            old_name='id',
            new_name='package_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ussd_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ussd_response',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ussd_status',
        ),
        migrations.DeleteModel(
            name='USSDLog',
        ),
    ]
