# Generated by Django 5.1.7 on 2025-04-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0021_alter_package_options_rename_id_package_package_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_id',
            new_name='id',
        ),
    ]
