# Generated by Django 5.1.7 on 2025-04-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno', '0022_alter_package_options_rename_package_id_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='retry',
        ),
        migrations.RemoveField(
            model_name='package',
            name='ussd',
        ),
        migrations.RemoveField(
            model_name='package',
            name='validity',
        ),
    ]
